// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUwoPS8vS_-wLt3H_BfHatx2MnTQ0sBlY',
    appId: '1:708198905074:web:895fd13894dffc10a34c6b',
    messagingSenderId: '708198905074',
    projectId: 'flutter-application-1-6c4b0',
    authDomain: 'flutter-application-1-6c4b0.firebaseapp.com',
    storageBucket: 'flutter-application-1-6c4b0.firebasestorage.app',
    measurementId: 'G-0F0QSH8H43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYOvkRTO7J6B4cRjVSTFfRnS7JDbE_zg',
    appId: '1:708198905074:android:500c32fbcdacb26ea34c6b',
    messagingSenderId: '708198905074',
    projectId: 'flutter-application-1-6c4b0',
    storageBucket: 'flutter-application-1-6c4b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_KG0gIX0jJocVLLZrzwkqdPGX-FQXXk',
    appId: '1:708198905074:ios:99a11eb0ad24c4baa34c6b',
    messagingSenderId: '708198905074',
    projectId: 'flutter-application-1-6c4b0',
    storageBucket: 'flutter-application-1-6c4b0.firebasestorage.app',
    iosClientId: '708198905074-sou9c5fci3fstr6oqbhj05dmai7733ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_KG0gIX0jJocVLLZrzwkqdPGX-FQXXk',
    appId: '1:708198905074:ios:99a11eb0ad24c4baa34c6b',
    messagingSenderId: '708198905074',
    projectId: 'flutter-application-1-6c4b0',
    storageBucket: 'flutter-application-1-6c4b0.firebasestorage.app',
    iosClientId: '708198905074-sou9c5fci3fstr6oqbhj05dmai7733ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUwoPS8vS_-wLt3H_BfHatx2MnTQ0sBlY',
    appId: '1:708198905074:web:33abef508bb582fea34c6b',
    messagingSenderId: '708198905074',
    projectId: 'flutter-application-1-6c4b0',
    authDomain: 'flutter-application-1-6c4b0.firebaseapp.com',
    storageBucket: 'flutter-application-1-6c4b0.firebasestorage.app',
    measurementId: 'G-H536QGYH5D',
  );

}